Building trics


Requirements:

    make, gcc, libncurses5-dev, libsdl2-dev

    valgrind (used for mem checks)

Set-up:

    To compile the project simply run: `make`

    Binary will be placed to bin/trics

Makefile targets:

    clean     - clean everything, delete object files and target dir
    run       - make and run
    run-check - make and run with mem check

Environment:
    BUILD     - if set to "debug" will compile with debug symbols
                BUILD=debug make
