Building trics


Requirements:

    make, gcc, libncurses5-dev

    valgrind (used for mem checks)

Set-up:

    To compile the project simply run: `make`

    Binary will be placed to bin/trics

Makefile targets:

    clean   - clean everything, delete object files and target dir
