name: build

on: [push]

jobs:
  build:
     strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Install libncurses5-dev
      run: sudo apt install libncurses5-dev

    - uses: actions/checkout@v1
    - name: make
      run: make
