name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: setup
      run: apt install libncurses5-dev

    - uses: actions/checkout@v1
    - name: make
      run: make
